#EXPERIMENT 11

1]Convert 1-D array with 8 elements into a 2-D array in Python

In [ ]:
import numpy as np
# 1-D array having elements [1 2 3 4 5 6 7 8]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr1 = arr.reshape(4, 2)
print ('After reshaping having dimension 4x2:')
print (arr1)
print ('\n')
arr2 = arr.reshape(2, 4)
print ('After reshaping having dimension 2x4:')
print (arr2)
print ('\n')


After reshaping having dimension 4x2:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


After reshaping having dimension 2x4:
[[1 2 3 4]
 [5 6 7 8]]




2)Create a 3D numpy array of ones in Python
import numpy as np

In [ ]:
the_3d_array = np.ones((2, 2, 2))
print(the_3d_array)


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


3)Calculate the sum of every column in a NumPy array in Python

In [ ]:
import numpy
# explicit function to compute column wise sum
def colsum(arr, n, m):
  for i in range(n):
    su = 0;
    for j in range(m):
      su += arr[j][i]
    print(su, end = " ")
# creating the 2D Array
TwoDList = [[1, 2, 3], [4, 5, 6],
[7, 8, 9], [10, 11, 12]]
TwoDArray = numpy.array(TwoDList)
# displaying the 2D Array
print("2D Array:")
print(TwoDArray)
# printing the sum of each column
print("\nColumn-wise Sum:")
colsum(TwoDArray, len(TwoDArray[0]), len(TwoDArray))

2D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Column-wise Sum:
22 26 30 

4)Get the transpose of an numpy array in python

In [ ]:
import numpy as np
a= np.arange(12).reshape((4,3))
a
print(a)
b=np.transpose(a)
b
print(b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


5)Sum Last Column only in Numpy

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
column_sums = newarr[:, 0].sum()
print(column_sums)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
22
